version: 2.1
orbs:
  python: circleci/python@2.0.3
  
jobs:
  # job to build Docker container containing Python application
  build:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python3 -m unittest test_wmata_api.py
      
